- CHANGELOG.md
- Cargo.toml
- src/functions.rs
- src/parser.rs
- tests/it/parser.rs
- Allow parse escaped white space
- Functions compatible with the invalid JSON and will not panic
> Fix: Allow parse escaped white space

- src/de.rs
- src/functions.rs
- src/value.rs
- tests/it/functions.rs
`to_string` function adds backslash for escaped characters, for example, `a"bc` will be displayed as `a\"bc`.
> Fix: json `to_string` function adds backslash for escaped characters

- src/parser.rs
- src/util.rs
- tests/it/parser.rs
Support parsing Unicode characters enclosed in brackets, for example: `"\u{fe0f}"`.
> Fix: Support parsing Unicode characters enclosed in brackets

- src/functions.rs
- src/util.rs
- tests/it/functions.rs
- tests/it/parser.rs
Fix some special characters display errors.
for example, display `⚠️` as `⚠\u{fe0f}`
> Fix: Fix some special characters display errors

- Cargo.toml
- src/constants.rs
- src/functions.rs
- src/parser.rs
- tests/it/functions.rs
- tests/it/parser.rs
- `convert_to_comparable` convert JSONB value to comparable format.
- `rand_value` generate a random JSONB value.
- Modify the compare rule for Object types, the larger the key, the larger the Object.
- Parse string allow control characters.
the comparable format is used by row sort in https://github.com/datafuselabs/databend/pull/11765
> Feat: Add function convert_to_comparable, rand_value

- src/functions.rs
- src/jsonpath/selector.rs
- tests/it/functions.rs
improve json path selector using less memory
- The `Selector` records the `Position` of the value in the original value during the query process to avoid storing temporary data allocation memory.
- The result data is placed directly into the builder's buffer to avoid storing result data allocation memory.
> Feat: improve json path selector using less memory

- src/functions.rs
- tests/it/functions.rs
Support traverse_check_string function
> Feat: Support traverse_check_string function

- src/functions.rs
- tests/it/functions.rs
Added `to_pretty_string`, which is necessary for https://github.com/datafuselabs/databend/issues/11270.
> feat: to_pretty_string api

- src/functions.rs
- tests/it/functions.rs
Added strip_nulls, related with https://github.com/datafuselabs/databend/issues/11270.
> feat: strip_nulls api

- src/constants.rs
- src/functions.rs
- tests/it/functions.rs
Added `type_of`. Related to https://github.com/datafuselabs/databend/issues/11270
> feat: type_of api

- src/functions.rs
- tests/it/functions.rs
Added `object_each`. Related to https://github.com/datafuselabs/databend/issues/11270
> feat: add object_each

- src/functions.rs
- tests/it/functions.rs
Added `get_by_keypath` (supporting operators `#>`, `#>>`). Related to https://github.com/datafuselabs/databend/issues/11270
> feat: add get_by_keypath

- src/functions.rs
- tests/it/functions.rs
Added  `exists_any_keys` & `exists_all_keys` (supporting operators `?|`, `?`, `?&` for https://github.com/datafuselabs/databend/issues/11270).
Searching object key doesn't seems to be optimal. We can optimize it to logarithmic via bsearch, but we should add offset-encoding support at first (like postgres does).
> feat: add exists_any_keys & exists_all_keys

- src/functions.rs
- src/value.rs
- tests/it/functions.rs
Added `contains` function (supporting `@>` `<@` operators for https://github.com/datafuselabs/databend/issues/11270).
I've used implementation from postgres as reference. https://github.com/postgres/postgres/blob/23c8c0c8f4721db693ef908c22f7cf754e6852a9/src/backend/utils/adt/jsonb_util.c#L1064C9-L1064C9
> feat: added contains api

- src/error.rs
- src/functions.rs
- src/jsonpath/parser.rs
- src/jsonpath/path.rs
- src/jsonpath/selector.rs
- tests/it/functions.rs
- tests/it/jsonpath_parser.rs
- tests/it/testdata/json_path.txt
1. Added support of jsonpath predicates;
2. Added `path_match` function (supporting `@@` and `json_path_match` for https://github.com/datafuselabs/databend/issues/11270);
Here I've tried to achieve the same behaviour of predicates like postgres has:
1. Selecting the result of the predicate path from json should return the predicate result itself, so `Selector::select` returns `true` or `false` in jsonb format;
2. `json_path_exists` always returns `true` on predicates, because  selector always has the result on it (`true` or `false`)
3. `@` is forbidden in predicate expression;
I've found the good explanation here https://justatheory.com/2023/10/sql-jsonpath-operators/
> feat: jsonpath predicate support

- Cargo.toml
- benches/strip_nulls.rs
- src/builder.rs
- src/functions.rs
- src/iterator.rs
- src/lib.rs
- tests/it/functions.rs
1. Added a builder api, which allows a json modification without the full deserialisation;
2. Added `concat` for https://github.com/datafuselabs/databend/issues/11270;
3. Moved `strip_nulls` to the new builder;
Also, added a benchmark for comparing the `strip_nulls` implementations.
Results for m1 pro are:
```
strip_nulls_deser[./data/canada.json]
time:   [5.5970 ms 5.6163 ms 5.6352 ms]
strip_nulls_fast[./data/canada.json]
time:   [2.8134 ms 2.8249 ms 2.8363 ms]
Benchmarking strip_nulls_deser[./data/twitter.json]: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 8.8s, enable flat sampling, or reduce sample count to 50.
strip_nulls_deser[./data/twitter.json]
time:   [1.7488 ms 1.7705 ms 1.8024 ms]
Found 4 outliers among 100 …
```
> feat: add concat & improve strip_nulls

- src/builder.rs
- src/functions.rs
- tests/it/functions.rs
Fix `jentry` length encoding for containers in `concat` and `builder`.
Discovered while testing in databend. Seems that the encoded len in the container `jentry` is not using in serde. So the previous tests were green :)
> fix: builder&concat container jentry len fix

- src/error.rs
- src/functions.rs
- src/jsonpath/selector.rs
- src/lib.rs
- tests/it/functions.rs
Added `delete_by_index` and `delete_by_name` (supporting delete operators for https://github.com/datafuselabs/databend/issues/11270)
> feat: add delete_by_index & delete_by_name

- Cargo.toml
- src/error.rs
- src/functions.rs
- src/number.rs
- tests/it/functions.rs
- support convert `jsonb` value to `serde_json` value
- use `itoa` and `ryu` convert number to string
> feat: support convert jsonb value to serde_json value

- src/jsonpath/parser.rs
- src/jsonpath/path.rs
- src/jsonpath/selector.rs
- tests/it/functions.rs
- tests/it/jsonpath_parser.rs
- tests/it/testdata/json_path.txt
Added jsonpath exists filter expression.
Related #12
> feat(jsonpath): add exists filter expression

- CHANGELOG.md
- Cargo.toml
> Bump to version 0.4.0

- benches/get_path.rs
- src/error.rs
- src/functions.rs
- src/jsonpath/selector.rs
- tests/it/functions.rs
jsonpath selector functions return `Result` instead of using `unwrap` function, prevents panic caused by handing invalid jsonb data
> fix: fix jsonpath selector unwrap panic

- src/de.rs
- src/error.rs
- src/functions.rs
- src/jsonpath/selector.rs
- src/number.rs
- tests/it/functions.rs
fix compare jsonb object value panic
https://github.com/databendlabs/databend/issues/16554
> fix: fix compare object value with different length panic

- src/functions.rs
- src/jentry.rs
- tests/it/functions.rs
Support following json array functions:
-  `array_insert`
- `array_distinct`
- `array_intersection`
- `array_except`
- `array_overlap`
> Feat: Support json array functions

- src/de.rs
- src/lib.rs
Currently we use `from_slice` to parse jsonb to `Value`, but cannot distinguish jsonb and json strings for compatibility. This patch add a function for parsing jsonb only similar to `parse_value`.
> feat: add a function to parse jsonb only

- src/core/databend/iterator.rs
- src/core/databend/ser.rs
- src/core/databend/util.rs
- src/core/item.rs
- src/functions/path.rs
- src/functions/scalar.rs
- src/jsonpath/selector.rs
- src/raw.rs
1. Refactor the implementation of get object value by the key name, avoid reading all the key jentries at one time, change to a lazy mode, only read when need, avoid the performance impact of reading a lot of keys.
2. Check whether the length of the object's key is equal to the needed key name first, to reduce the call of `equal` function.
3. Avoid using `Deserializer` to convert the type of data inside the function, because usually we already know the type, we can extract it directly to avoid extra judgement in the conversion process of `Deserializer`.
> Refactor: get object value by key name improve performance

- Cargo.toml
- src/core/databend/iterator.rs
- src/functions/path.rs
- src/jsonpath/mod.rs
- src/jsonpath/parser.rs
- src/jsonpath/path.rs
- src/jsonpath/selector.rs
- src/number.rs
- tests/it/functions.rs
- tests/it/jsonpath_parser.rs
- tests/it/testdata/json_path.txt
> feat: json path support recursive wildcard member accessor `.**` syntax

- Cargo.toml
- src/jsonpath/parser.rs
- src/jsonpath/path.rs
- src/jsonpath/selector.rs
- src/keypath.rs
- tests/it/testdata/json_path.txt
- bump nom 8.0.0
- refactor `ArithmeticOperator`
- remove unused println
> chore: Bump nom 8.0.0

- Cargo.toml
- src/constants.rs
- src/core/databend/builder.rs
- src/core/databend/constants.rs
- src/core/databend/de.rs
- src/core/databend/jentry.rs
- src/core/databend/ser.rs
- src/core/databend/util.rs
- src/core/item.rs
- src/error.rs
- src/extension.rs
- src/from.rs
- src/functions/operator.rs
- src/functions/scalar.rs
- src/lib.rs
- src/number.rs
- src/raw.rs
- src/value.rs
- tests/it/decode.rs
- tests/it/encode.rs
- tests/it/functions.rs
support extension types
- binary
- decimal
- date
- timestamp
- timestamp_tz
- interval
jsonb consists of three parts: `header`, `jentry`, and `payload`. Both the `header` and `jentry` are of fixed length of 32 bits, while the `payload` is not fixed in length and varies according to the specific data type. The overall structure is shown in the following figure:
```
┌────────┬─────────┬─────────┬─────┬─────────┬──────────┬──────────┬─────┬──────────┐
│ header │ jentry1 │ jentry2 │ ... │ jentryN │ payload1 │ payload2 │ ... │ payloadN │
└────────┴─────────┴─────────┴─────┴─────────┴──────────┴──────────┴─────┴──────────┘
```
The `header` contains the type of data and the number of internal elements
```
┌─────────────┬──────────────────────┐
│ type(3 bit) │ item numbers(29 bit) │ …
```
> Feat: support extension types

- Cargo.toml
- src/core/databend/de.rs
- src/core/databend/util.rs
- src/error.rs
- src/functions/scalar.rs
- src/number.rs
- src/parser.rs
- src/util.rs
- tests/it/parser.rs
This pull request introduces support for [JSON5 syntax](https://json5.org/) when parsing JSON data into the JSONB format. This enhancement provides a more flexible and developer-friendly way to represent JSON data.
Key features included in this PR:
- **Hexadecimal Numbers:**  Support for hexadecimal number representation, including both integer and floating-point formats (e.g., `0xabc`, `0X123.56`).
- **NaN and Infinity:**  Parsing support for `NaN` (Not a Number) and `Infinity` values, aligning with JSON5 specifications.
- **Single-Quoted Strings:**  Strings can now be enclosed in single quotes (e.g., `'abcd'`).
- **Unquoted Object Keys:**  Object keys are now allowed without quotes (e.g., `{ key: "value" }`).
- **Case-Insensitive Boolean and Null:**  The parser now supports …
> feat: Support parse extended json5 syntax
